# Generated by Django 6.0.3 on 2026-03-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_remove_timetable_data_timetable_cells_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mtn_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "airtel_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("current_term", models.IntegerField(default=2)),
                ("current_year", models.IntegerField(default=2025)),
            ],
            options={
                "verbose_name_plural": "School Settings",
            },
        ),
        migrations.RemoveField(
            model_name="student",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="student",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="student",
            name="home_address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="medical_conditions",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_phone2",
        ),
        migrations.RemoveField(
            model_name="student",
            name="previous_school",
        ),
        migrations.RemoveField(
            model_name="student",
            name="transport_route",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="email",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="user",
        ),
        migrations.AddField(
            model_name="student",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_info",
                to="school.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_failed_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
